name: commitlint
description: Lint commit messages with GitHub Actions.
author: remarkablemark

inputs:
  config:
    description: Config to enforce conventional commits
    default: '@commitlint/config-conventional'

  from:
    description: Lower end of the commit range to lint
    default: HEAD~1

  version:
    description: Version of @commitlint/cli
    default: latest

runs:
  using: composite
  steps:
    - name: Install commitlint
      shell: bash
      run: |
        npm install --silent --global commitlint@${{ inputs.version }}
        commitlint --version

    - name: Get config
      shell: bash
      run: |
        if [[ grep --quiet '"@commitlint/' package.json ]]; then
          npm install --silent
          exit 0
        fi

        CONFIG=$(commitlint --print-config --no-color)

        RULES_LENGTH=$(node <<EOF
          const config = $CONFIG;
          console.log(Object.keys(config.rules).length);
        EOF
        )

        if [[ $RULES_LENGTH == 0 ]]; then
          npm install --silent --no-save ${{ inputs.config }}
          cat <<'EOF' > .commitlintrc.json
          {
            "extends": ["${{ inputs.config }}"],
            "rules": {
              "body-max-line-length": [1, "always", 100],
              "footer-max-line-length": [1, "always", 100]
            }
          }
        EOF
        fi

    - name: Run commitlint
      shell: bash
      run: commitlint --from=${{ inputs.from }}

    - name: Cleanup
      shell: bash
      run: |
        npm uninstall --silent --global commitlint
        git reset --hard && git clean -d --force

branding:
  icon: terminal
  color: gray-dark
