name: commitlint
description: Lint commit messages with GitHub Actions.
author: remarkablemark
inputs:
  version:
    description: Description
    default: 1.2.3
runs:
  using: composite
  steps:
    - run: |
        echo 'version: ${{ inputs.version }}'
      shell: bash
branding:
  icon: terminal
  color: gray-dark
